export default () => ({
  nodeEnv: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '3000', 10),
  databaseUrl: process.env.DATABASE_PUBLIC_URL,
  dbHost: process.env.PGHOST || 'localhost',
  dbPort: parseInt(process.env.PGPORT || '5432', 10),
  dbUser: process.env.PGUSER || 'postgres',
  dbPass: process.env.PGPASSWORD || 'secret',
  dbName: process.env.PGDATABASE || 'clientes_puntos',
  authServerUrl: process.env.KEYCLOAK_URL,
  realm: process.env.KEYCLOAK_REALM,
  clientId: process.env.KEYCLOAK_CLIENT_ID,
  secret: process.env.KEYCLOAK_CLIENT_SECRET || 'secret',
  campania: process.env.CAMPANIA_ID || 1883,
  redisHost: process.env.REDISHOST,
  redisPort: process.env.REDISPORT,
  redisUser: process.env.REDISUSER,
  redisPass: process.env.REDIS_PASSWORD,
  redisUrl: process.env.REDIS_URL,
});
