export default () => ({
  nodeEnv: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT || '3000', 10),
  databaseUrl: process.env.DATABASE_URL,
  dbHost: process.env.DB_HOST || 'localhost',
  dbPort: parseInt(process.env.DB_PORT || '5432', 10),
  dbUser: process.env.DB_USER || 'postgres',
  dbPass: process.env.DB_PASS || 'secret',
  dbName: process.env.DB_NAME || 'clientes_puntos',
  authServerUrl: process.env.KEYCLOAK_URL,
  realm: process.env.KEYCLOAK_REALM,
  clientId: process.env.KEYCLOAK_CLIENT_ID,
  secret: process.env.KEYCLOAK_CLIENT_SECRET || 'secret',
  campania: process.env.CAMPANIA_ID || 1883,
  redisHost: process.env.REDISHOST,
  redisPort: process.env.REDISPORT,
  redisUser: process.env.REDISUSER,
  redisPass: process.env.REDIS_PASSWORD,
  redisUrl: process.env.REDIS_URL,
});
